# Generated by Django 4.1.4 on 2024-07-30 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Acompanhamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("ativo", models.BooleanField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "4 - Acompanhamento",
                "verbose_name_plural": "4 - Acompanhamento",
            },
        ),
        migrations.CreateModel(
            name="MontaPizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(null=True)),
                ("acompanhamentos", models.ManyToManyField(to="myapp.acompanhamento")),
            ],
            options={
                "verbose_name": "B - MontaPizza",
                "verbose_name_plural": "B - MontaPizza",
            },
        ),
        migrations.CreateModel(
            name="Sabor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("ativo", models.BooleanField()),
            ],
            options={
                "verbose_name": "3 - Sabor",
                "verbose_name_plural": "3 - Sabor",
            },
        ),
        migrations.CreateModel(
            name="Tamanho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("quantidade_fatias", models.PositiveIntegerField()),
                ("ativo", models.BooleanField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "1 - Tamanho",
                "verbose_name_plural": "1 - Tamanho",
            },
        ),
        migrations.CreateModel(
            name="TipoSabor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("ativo", models.BooleanField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "2 - TipoSabor",
                "verbose_name_plural": "2 - TipoSabor",
            },
        ),
        migrations.CreateModel(
            name="SelSabor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_fatias", models.PositiveIntegerField()),
                (
                    "pizza",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sabor_set",
                        to="myapp.montapizza",
                    ),
                ),
                (
                    "sabor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sel_sabores",
                        to="myapp.sabor",
                    ),
                ),
            ],
            options={
                "verbose_name": "A - SelSabor",
                "verbose_name_plural": "A - SelSabor",
            },
        ),
        migrations.CreateModel(
            name="SacolaItens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("pizzas", models.ManyToManyField(to="myapp.montapizza")),
            ],
            options={
                "verbose_name": "C - SacolaItens",
                "verbose_name_plural": "C - SacolaItens",
            },
        ),
        migrations.AddField(
            model_name="sabor",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sabores",
                to="myapp.tiposabor",
            ),
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_pedido", models.DateTimeField(auto_now_add=True, null=True)),
                ("status", models.BooleanField()),
                ("pago", models.BooleanField()),
                (
                    "itens_da_sacola",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.sacolaitens",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "D - Pedido",
                "verbose_name_plural": "D - Pedido",
            },
        ),
        migrations.AddField(
            model_name="montapizza",
            name="tamanho",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pizzas",
                to="myapp.tamanho",
            ),
        ),
    ]
