# Generated by Django 4.1.4 on 2024-07-31 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acompanhamento',
            options={'verbose_name': '4 - Acompanhamento', 'verbose_name_plural': '4 - Acompanhamento'},
        ),
        migrations.AlterModelOptions(
            name='tamanho',
            options={'verbose_name': '1 - Tamanho', 'verbose_name_plural': '1 - Tamanho'},
        ),
    ]
