# Generated by Django 4.1.4 on 2024-07-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_acompanhamento_options_alter_tamanho_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacolaitens',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
