# Generated by Django 4.1.4 on 2024-07-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_sacolaitens_preco"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selsabor",
            name="quantidade_fatias",
        ),
    ]
