# Generated by Django 4.1.4 on 2024-07-29 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0004_cobertura"),
    ]

    operations = [
        migrations.CreateModel(
            name="MontaPote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(null=True)),
                ("coberturas", models.ManyToManyField(to="myapp.cobertura")),
                (
                    "embalagem",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embalagem",
                        to="myapp.embalagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "B - MontaPote",
                "verbose_name_plural": "B - MontaPote",
            },
        ),
        migrations.CreateModel(
            name="SelSabor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_bolas", models.PositiveIntegerField()),
                (
                    "pote",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pote",
                        to="myapp.montapote",
                    ),
                ),
                (
                    "sabor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sabor",
                        to="myapp.sabor",
                    ),
                ),
            ],
            options={
                "verbose_name": "A - SelSabor",
                "verbose_name_plural": "A - SelSabor",
            },
        ),
        migrations.CreateModel(
            name="SacolaItens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("potes", models.ManyToManyField(to="myapp.montapote")),
            ],
            options={
                "verbose_name": "C - SacolaItens",
                "verbose_name_plural": "C - SacolaItens",
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_pedido", models.DateTimeField(auto_now_add=True, null=True)),
                ("status", models.BooleanField()),
                ("pago", models.BooleanField()),
                (
                    "itens_da_sacola",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.sacolaitens",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedido_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "D - Pedido",
                "verbose_name_plural": "D - Pedido",
            },
        ),
    ]
